export const ROLE = 'ROLE';

export const baseUserVM = {
    sirname: '',
    name: '',
    middlename: '',
    birthDate: '',
    city: undefined,
    cityRegistered: undefined,
    citizenship: undefined,
    role: 'Клиент',
    disability: undefined,
    familyStatus: undefined,
    sex: false,
    passportSeria: '',
    passportNumber: '',
    passportGivenBy: '',
    passportGivenAt: '',
    passportIdentityNumber: '',
    placeOfBirth: '',
    addressLiving: '',
    homePhone: undefined,
    mobilePhone: undefined,
    emailAddress: undefined,
    workPlace: undefined,
    workPosition: undefined,
    addressRegistered: '',
    pensioner: false,
    militarian: false,
    monthIncome: undefined
}